module.exports = Object.freeze({
  CURRENCY: "VND",
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 20,
  MAX_LIMIT: 100,
  JSON_BODY_LIMIT: "100kb",
  USER_STATUSES: ["ACTIVE", "BLOCKED", "DELETED"],
  PROPERTY_STATUSES: ["ACTIVE", "INACTIVE"],
  AVAILABILITY_STATUSES: ["OPEN", "HELD", "BOOKED", "CLOSED"],
  BOOKING_STATUSES: [
    "PENDING_PAYMENT",
    "CONFIRMED",
    "CANCELLED",
    "EXPIRED",
    "COMPLETED",
  ],
  PAYMENT_STATUSES: ["CREATED", "PENDING", "SUCCEEDED", "FAILED", "EXPIRED"],
});
